spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/eBanking_test
    username: test_user
    password: test_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  logging:
    level:
      root: WARN
      org.springframework: INFO
