spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eBanking
    username: postgres
    password: soumia
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: eBanking

server:
  port: 8082
