spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/prod_db
    username: postgres
    password: soumia
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: eBanking
server:
  port: 8080
